### ISSUE TITLE
Replace fprintf(stderr, ...) & exit with exceptions

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1010]
There are a bunch of places in our code base where we print an error to stderr and exit. We should throw exceptions instead!

Also, when possible the error messages should reflect actual instance data, like if we can't access a key in a dict, it's good if we can include the actual key in the error message.

```
kll@ThinkYoga:~/terastream/acton$ rg "^ *exit.1"
builtin/int.c
175:    exit(1);
217:    exit(1);
222:    exit(1);
372:    exit(1);
381:    exit(1);
387:    exit(1);
393:    exit(1);
624:        exit(1);

builtin/exceptions.c
95:  exit(1);

builtin/timsort.c
372:      exit(1);
```

**Comment by sydow** [comment]
I am at fault for some of these... I will fix them soon. I excuse myself with
- I forget exactly the parameters of RAISE
- the knowledge that RAISE just prints to stderr and exits...
But, of course, for the future it will be different.

**Comment by plajjan** [comment]
I just updated the issue description with the current list of places we do exit in builtins. I think all!? of them should go away and be replaced by exceptions, right

**Comment by sydow** [comment]
I accept the assignment, but

- are we ready to *really* throw exceptions yet? 
If I define

def inv(x : int) -> float:
    if x==0:
        raise ValueError("inv: division by zero")
    else:
        return 1/x
    
and then run inv(0) the program hangs rather than aborts. I don’t think we want that so I would prefer to wait to throw exceptions until unhandled exceptions trigger program abortion. And to change to $RAISE (which just is a hidden exit(1)) now when we very soon (?) will have real exceptions seems unnecessary.



- I don’t know what to write in C in builtin/*.c to throw real exceptions. What should replace

       $RAISE((B_BaseException)$NEW(B_ValueError,to$str(errmsg)));
 


- I am not convinced that we want *all* exit(1)’s to be replaced by raising an exception, but probably most should. For instance, in 

B_int B_intG_new(B_atom a) 

in int.c, which creates an int from an atom, we try ISINSTANCE(a,T) for all atomic types T. After that code follows now

    fprintf(stderr,"internal error: B_intG_new: argument not of atomic type\n");
    exit(-1);

This code should be unreachable for type-checked programs. One could argue for these two lines to be removed (since this code location is unreachable) or one could argue to keep them (since there might be a bug in the compiler and then this error message could be helpful) but I don’t think one could argue to raise an exception. Or?

Björn

**Comment by plajjan** [comment]
@nordlander so that means it is correct to change to `$RAISE` now right? and it will start doing the correct thing later on when you are done?

@sydow I agree that internal errors and similar should exit immediately so we can find such things as early as possible. I would prefer to wrap it up into some function / macro that makes that more clear. Like `INTERNAL_ERROR("Something bad happened");` or similar, other ideas?

@nordlander what did we settle on for actors? Unhandled exceptions are essentially ignored, right? Like the current method obviously stops executing but the actor continues to exist right? So we won't actually abort the whole program, even when you are done, it will "just hang there"!?

**Comment by nordlander** [comment]
Yes, use $RAISE freely, except when it occurs in CPS converted code (don't think we have any example of that combination yet). There one must use a forthcoming function $RAISEc, but more on that later.

In actors, unhandled exceptions will just abort the current continuation, checkpoint the current state, re-raise the exception in any waiting client actors, and then consider the current message handled. I think this is the desired behavior, except that we might also want to log info about the failure somewhere (perhaps by simply increasing a counter). But the actor itself will persist in the state of its latest checkpoint, ready to handle any remaining messages. It's not supposed to "hang" in the sense of not being responsive.
