### ISSUE TITLE
Improve type checker performance

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1025]
While performance isn't the top priority for us, Acton does need to be "fast enough". I don't think it's ok to spend multiple seconds of type checking for a relatively small program like the test_tcp_server (granted it might be the largest test program we have in this repo).

```
kll@ThinkYoga:~/terastream/acton/test$ /home/kll/terastream/acton/dist/bin/actonc --timing --always-build --dev rts_db/test_tcp_server.act 
Building file rts_db/test_tcp_server.act
Reading file rts_db/test_tcp_server.act:  0.001 s
Parsing file rts_db/test_tcp_server.act:  0.058 s
  Compiling test_tcp_server.act for development
    Pass: Make environment:  0.001 s
    Pass: Kinds check     :  0.000 s
    Pass: Type check      :  6.026 s
    Pass: Normalizer      :  0.000 s
    Pass: Deactorizer     :  0.000 s
    Pass: CPS             :  0.000 s
    Pass: Lambda Lifting  :  0.108 s
    Pass: Generating code :  0.000 s
    Pass: Writing code    :  0.000 s
    Pass: C compilation   :  1.383 s
   Finished compilation in   7.518 s
Building executable /home/kll/terastream/acton/test/rts_db/test_tcp_server
kll@ThinkYoga:~/terastream/acton/test$ 
```

With my power cable unplugged so CPU is running in more of a battery saving mode it gets even worse, taking twice the above.

is this haskell lazy eval getting us int some bind? I believe we need to think enough about performance to avoid this at least...

My experience is that it's quite simple to improve the situation by adding some explicit type signatures somewhere but it's not as easy knowing where to do that. Could we add simple metrics to easily figure that out?

**Comment by nordlander** [comment]
This is likely caused by some accidental loss of sharing that results in exponential complexity. I encountered this problem once in the previous Acton type-checker, was quite easy to fix.

Akternatively, it could be the solver being fooled into searching some unnecessarily large solution space. Here as well the fix should be easy, once the root cause is found.

In any case I’ll look into it.

31 okt. 2022 kl. 14:47 skrev Kristian Larsson ***@***.***>:

﻿

While performance isn't the top priority for us, Acton does need to be "fast enough". I don't think it's ok to spend multiple seconds of type checking for a relatively small program like the test_tcp_server (granted it might be the largest test program we have in this repo).

***@***.***:~/terastream/acton/test$ /home/kll/terastream/acton/dist/bin/actonc --timing --always-build --dev rts_db/test_tcp_server.act
Building file rts_db/test_tcp_server.act
Reading file rts_db/test_tcp_server.act:  0.001 s
Parsing file rts_db/test_tcp_server.act:  0.058 s
  Compiling test_tcp_server.act for development
    Pass: Make environment:  0.001 s
    Pass: Kinds check     :  0.000 s
    Pass: Type check      :  6.026 s
    Pass: Normalizer      :  0.000 s
    Pass: Deactorizer     :  0.000 s
    Pass: CPS             :  0.000 s
    Pass: Lambda Lifting  :  0.108 s
    Pass: Generating code :  0.000 s
    Pass: Writing code    :  0.000 s
    Pass: C compilation   :  1.383 s
   Finished compilation in   7.518 s
Building executable /home/kll/terastream/acton/test/rts_db/test_tcp_server
***@***.***:~/terastream/acton/test$


With my power cable unplugged so CPU is running in more of a battery saving mode it gets even worse, taking twice the above.

is this haskell lazy eval getting us int some bind? I believe we need to think enough about performance to avoid this at least...

My experience is that it's quite simple to improve the situation by adding some explicit type signatures somewhere but it's not as easy knowing where to do that. Could we add simple metrics to easily figure that out?

**Comment by nordlander** [comment]
Turns out that a major reason for the bad performance is that the solver subroutine 'simplify' doesn't split its input into non-overlapping sets like the solver proper does, which causes a lot of repeated traversals of constraint sets that are unaffected by the current improvement step. An easy thing to fix, and the solution I've pushed seems to bring down the type-checker execution time to less than half on the problematic example.

But I've also noted some other wasteful behavior of the solver which I intend to understand better in order to correct. Keeping the issue open for this purpose!

**Comment by plajjan** [comment]
@nordlander is there anything besides the solver that could take time during the type checking pass in the compiler? I'm thinking of this line:
```haskell
                      (iface,tchecked,typeEnv) <- Acton.Types.reconstruct outbase env kchecked
```
which is what I've called "type checking" (if compiler is run with --timings) even though the function is called something else.

We have some programs that are rather slow to type check and I assume it is type inference making bad guesses / running through lots of potential solutions. Or should we have a counter or something to indicate how many potential solutions we've run through as an indicator?

The slow program is acton-streamer, which you have access to... just build the thing. Some files are > 30 seconds for me.

**Comment by nordlander** [comment]
A quick glimpse of what to expect from the improved solver: I just managed to compile nsoapi/schema.act in 1 min 55 sec, compared to 10 min 41 sec when using the current main branch.

I still think 1:55 is way too much, but at least this shows that my current line of attack is bearing fruit!

**Comment by plajjan** [comment]
We are now down to a few seconds. I'm going to close this issue since the fixes are in that brings performance to a reasonable and acceptable level. There are no currently planned improvements and nothing immediately actionable, so closing.

We can open other more specific issues in the future to further improve performance if the need arise.
