### ISSUE TITLE
list.__bool__() returns True for empty lists

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#1193]
### Acton Version

0.14.2.20230221.16.25.49

### Steps to Reproduce

```
actor main(env):
    a: list[str] = []
    if a:
        print(a[0])
    await async env.exit(0)
```

### Expected Behavior

`list.__bool_(self)` to return `False` for empty `self`

### Actual Behavior

```
getitem: indexing outside list
```

**Comment by plajjan** [comment]
Not sure if this is straight forward or if there is any doubt about the actual solution? @nordlander ?

**Comment by sydow** [comment]
The problem was that the method table for lists contained in the slot for __bool__ not the custom method defined in list.c but the default method inherited from value. The method table is populated in builtin/__builtin__.c, using C code generated by actonc from __builtin__.act. Similar errors have occurred before and are not well understood. A careful manual check of __builtin__.c seems necessary, but is not done in this fix.

**Comment by plajjan** [comment]
Just wanna +1 the added test in list.act, I think that's our best approach to avoid this sort of problem in the future if / when we regenerate C code, which feels likely to happen at some point.
