### ISSUE TITLE
R_CONT vs RU_CONT

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1387]
We use `return $R_CONT...` in a lot of .ext.c code. I've seen newer generated code say `return $RU_CONT`. Has it changed name or so?

**Comment by nordlander** [comment]
The added U character is a consequence of our new scheme for compiler-generated names. Internal names like $R_CONT should preferably be excluded from this name-mangling, but since all these are soon to be overhauled anyway (and loose the $ prefix), I've left it all for later. Currently $RU_CONT is just an alias for $R_CONT.

**Comment by nordlander** [comment]
Closing, that is.
