### ISSUE TITLE
Variable input to isinstance?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1515]
I was trying to implement a `assertIsInstance(a, b, msg)` function for the `testing` library but it fails to compile because `isinstance()` requires an actual type as the second argument. Here I am instead giving it a variable which should contain a type.

Is this just a bug or something that we have deliberately designed to be this way?

Is there a better way to implement the equivalent of `assertIsInstance` ? I mean, we are a static language, so maybe this whole thing, which is of course taken from Python, just doesn't make very much sense.

**Comment by nordlander** [comment]
This is indeed an example of where Python's dynamic features don't mix well with static typing!

The problem is that when used as an expression, a class name is assigned a _function type_ by the type-checker. That's because the typical thing you do with classes at run-time is to create instances of them. But `isinstance` doesn't care much about the constructor arguments of the referenced class, here it's just the class _ancestry_ that's the interesting aspect. And we have no way of capturing such information as a type, in fact I don't think many languages do. Just imagine what the type of `isinstance` would have to be if it were an ordinary library routine. An attempt like
```
   isinstance : [C, D(C)] => (C, D) -> bool
```
wouldn't work, because that would require the second argument to be an _instance_ of D, not a class in itself. This is why `isinstance` has to be a builtin primitive that's getting a special treatment by the type-checker.

I don't think there's a nice way of implementing the founction you want in Acton right now (just as there are no good means of abstracting over patterns and pattern-matching in Haskell). There is an avenue to explore which involves a more exoctic type system feature called 'typecase', but I'll have to read up a bit more on that topic before we can choose such a path.

**Comment by plajjan** [comment]
I don't think we should spend time on this now. I just wanted to raise the question since I've been hacking on a `testing` module.

Maybe the need for this just isn't very big, like one can rather easily implement this sort of type checking just using type signatures and perhaps manually calling isinstance and doing raise...

**Comment by plajjan** [comment]
There's nothing actionable here in the short term or even much longer term (sooo many items before on the TODO) so I'll close this. We're not going to implement this.

**Comment by plajjan** [comment]
I think we should simply document how users should deal with this. In Python it makes sense with isinstance checks since we know about types at run time. In Acton, we know about them at compile time. So an isinstance test should really just be a compilation error and we should encourage users to write their test code in a way that will error out at compilation.

So something like this:
```
a: ExpectedType = some_function()
```
