### ISSUE TITLE
Improve argparse to consume as many option values as it can

### ISSUE THREAD

**Issue by mzagozen** [actonlang/acton#1730]
### Proposal

I would like to parse the command line `["./app", "--text", "A", "B", "--verbose"]` such that the values `["A", "B"]` are assigned to `--text`:

```
def test_opts_nargs2():
    p = argparse.Parser()
    p.add_bool("verbose", "Enable verbose output")
    p.add_option("text", "strlist", "+", [], "Text field")

    args = p.parse(["./app", "--text", "A", "B", "--verbose"])
    if args.get_strlist("text") != ["A", "B"]:
        raise ValueError('opt strlist != ["A", "B"]')
    if args.get_bool("verbose") != True:
        raise ValueError("bool verbose != True")
```

### Motivation

This makes the behavior equivalent to Python argparse wrt consuming values.

### Alternatives

Of course appending to _strlist_ works as expected if each option is fully qualified with key and value: `["./app", "--text", "A", "--text", "B", "--verbose"]`

**Comment by plajjan** [comment]
So I think I rather deliberately tried to avoid ambiguous situations for the argument parser and accepting an arbitrary amount of argument values I think creates more ambiguity.

Python's argparse seems loaded with ambiguity and weird options, so overall I think it's a non-goal to replicate it completely and perhaps even partially. I think this aligns conceptually with how I see a large part of Acton, which is that it is Pythonic but not Python-compatible. The syntax is similar to Python's and I think it should embody some of the core concepts of why Python attracts people, like it is easy to use, there's usually very little boilerplate, make people productive with many high level concepts etc. I think we should strive to maintain that in Acton, but just copying stuff straight over from Python is not the way. We can never improve on something if we just copy it over. If we can implement something in as many lines as in Python, or fewer, and it is as easy or easier to read and explain to someone, then I think we've succeeded.

Most (or at least many!?) argument parsers in other languages do not have this functionality at all, so if we are to align on some idea of mainstream, I don't think it's the Python way. I haven't looked much into this, just did a query to ChatGPT which came back with mostly "not possible" or "the parser doesn't work on this high level anyway, so you'd have to implement stuff like that yourself".

But more than that, we have to be consistent with ourselves. Our argparse module has three fundamental "things":
- arguments, i.e. something that starts with the `-` prefix, like `--foo` or `-f` (although we don't actually support that yet), and they come in two flavours:
  - flag arguments, which do not take a value `--debug`
  - arguments that do take a value, like `--foo`
- positional arguments, which are really just argument values without a preceding `--foo` argument
- (sub-)commands, which use a sub-parser and are mapped to a function to run in Acton
  - git is a good example of this, like how `git commit` is the `commit` command which just does something entirely different than say `git status`.
  - in Acton argparse, each command has its own sub-parser so when the higher level parser encounters a sub-command, it invokes the sub-parser with the rest of argv
  - arguments are non-overlapping and additive between the parsers, so you can't have a `--foo` argument both in the top level parser and a `--foo` in a sub-parser that have different definitions

While `--` can be used to separate arguments and their values from positional arguments, the same is not true for commands. So if we built git and used this argparse module to implement `git commit` as a sub-command, do parsing the way you suggest in this ticket and then we add some argument that takes `nargs="+"` to the top level, we can't call sub-commands:

```python
actor test_cmd_strlist():
    proc def _commit(args):
        # do the commity stuff
        pass

    p = argparse.Parser()
    p.add_bool("verbose", "Enable verbose output")
    p.add_option("text", "strlist", "+", [], "Text field")
    pb = p.add_cmd("commit", "Commit stuff", _commit)

    _args = p.parse(["./app", "--text", "abc", "def", "commit"])
```

How would you disambiguate between values to `--text` and a command that follows? Do you see a way out of this?

Do you say that such a parser specification is invalid, like a parser cannot be allowed to implements nargs together with sub-commands? But it could if `nargs="+"` works the way it currently does, requiring each value to be preceded by the argument `--name`, right? So changing it from the current behavior to Python argparse style is a regression?

Or is this yet another option? `mval=True` (multiple values)

Note how it would be very doable (without ambiguity) to have a known number of argument values, like `nargs=2`, but I'm not sure if that helps anyone!?

**Comment by mzagozen** [comment]
> So I think I rather deliberately tried to avoid ambiguous situations for the argument parser and accepting an arbitrary amount of argument values I think creates more ambiguity. [...] Most (or at least many!?) argument parsers in other languages do not have this functionality at all, so if we are to align on some idea of mainstream, I don't think it's the Python way.

Right, I did not consider other parsers. Perhaps Python is an outlier with this mode and we should keep thins tidier here. The reason I started looking into this was to keep the xcon-ng interface compatible with xcon.py as a drop-in replacement. But of course it is does not have to be that way.

> Note how it would be very doable (without ambiguity) to have a known number of argument values, like nargs=2, but I'm not sure if that helps anyone!?

In this case it is not helpful, because the number of values is unknown.

I will close this and add a note in the application.

**Comment by plajjan** [comment]
I want to reiterate that one solution would be to accept the python argparse version of `nargs="+"` but only allow it when not mixing with sub-commands / parsers, since that would become ambiguous. We cannot validate and enforce such a constraint at compile time, but we can do it at run time when we construct the parser. I think this is acceptable since errors during construction of the parser will always show up when you run the program, regardless of what arguments you actually pass later on, so it's pretty close to "compile time check".

However, if we would do this, we'd probably have to call it something else than `nargs="+"` since the current version of acton argparse nargs="+" is non-ambiguous with sub-parsers and legal, we don't want to disallow it. So rather this "mval" version would need to be a new option and we could check during construction time that "mval" is not mixed with sub-commands.

Not sure what this looks like from a user perspective though, like would that feel inconsistent and counter-intuitive? I don't know. I doubt most people go "oh, I recognize this arg parse style, it's probably python argparse" and let that color their intuition about how options are parsed. I read man pages and --help output and simply do as told there, so if it say

```
program [--foo FOO]
```
then I'll give the FOO val to --foo. I think the convention is to specify in text that "this argument can be specified multiple times". For positional arguments there's this compact notation to indicate multiple arguments is allowed, like:
```
program [FOO ...]
```
maybe we could say:

```
program [--foo FOO...]
```
to mean the same thing, but I don't think there is a common convention for it. It's important that the end-user experience is a good one!

**Comment by plajjan** [comment]
Maybe also a source of confusion is that acton argparse use the nargs nomenclature to mean something different from what python argparse means. I think what acton argparse now implements, where we call it `nargs="+"` is done in python argparse with `action="append"`, right?

I think I did that mostly by coincidence, sort of bringing over the `nargs` name from python argparse but using it to mean something different in acton argparse... I don't think `action="append"` is particularly good though. WDYT?
