### ISSUE TITLE
Variable undefined in finally clause of try / except

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1749]
### Acton Version

v0.21.0

### Steps to Reproduce and Observed Behavior

I think `a` should be considered defined in the finally clause in this program
```python
def fun1() -> int:
    dummy: list[int] = []
    try:
        a = dummy[0]
    except IndexError:
        a = 1
    except Exception:
        a = 2
    finally:
        return a
```

but I get:
```
ERROR: Error when compiling exceptions_finally module: Compilation error

   |
12 |        return a
   |               ^
Name a is reserved but not yet defined
```

Doing return after the try / except works just fine though, like so:
```python
def fun1() -> int:
    dummy: list[int] = []
    try:
        a = dummy[0]
    except IndexError:
        a = 1
    except Exception:
        a = 2
    return a
```

### Expected Behavior

For `a` to be defined.

**Comment by plajjan** [comment]
I have added a test in #1752 that has a TODO entry on what to correct etc.

**Comment by nordlander** [comment]
Hmm, I don't think the behavior that's expected here is correct.

Admittedly it is the behavior one gets in Python, but Python happily agrees to read any variable, whether it has been assigned or not -- if not it just throws exception. In a compiled language like Acton we need to be more careful, so we can be absolutely sure that every variable that is read also has a value.

To see why the example is problematic, just change the line `a = 1` into `a = 1//0` and re-run in Python. Now three exceptions are raised: first the IndexError, then a DivisionByZero in the exception handler, and then, because the `finally` clause is asked to read an uninitialized variable, an UnboundLocalError.

Simply because a `finally` clause is expected to run _irrespective_ of what happens in its `try` statement, we cannot count on any of its defined variables to be stable when the `finally` clause is run. So our static scoping rules, which are based entirely on a program's syntax and not its semantics, conservatively ban all such accesses.

For a simpler but analogous example, consider the following code:
```
def fun2(x):
    if True:
        a = 1
    else:
        pass
    return a
```
Here one _could_ argue that returning `a` should be safe. But just replace `True` by some more complex expression that involves `x` and it becomes clear that some potentially very clever analysis might be required to sort out the visibility of `a`. 
In fact, scoping rules that depend on expression semantics is a very slippery slope that eventually leads to The Halting Problem! This is why Acton takes a simpler route and only passes on variables from an `if` statement that are defined in _all_  of its branches.

(As noted, the original example is indeed accepted by Acton if `return a` is moved after the `try` statement. This is safe precisely because such a return is only expected to run if the `try` statement falls through, in which case `a` is guaranteed to have a value.)

**Comment by plajjan** [comment]
Okay, I'll buy that, however annoying it might be. thanks :) Closing
