### ISSUE TITLE
Missing source location for `Escaping type variable E_3`

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1963]
This code:
```python
class Foo(object):
    def __init__(self, bars: [Bar]):
        self.bars = bars

class Bar(object):
    def __init__(self):
        pass
```

gives us this error
```console
kll@Kristians-MacBook-Air typeerrors % acton ex25.act
Building file ex25.act
  Compiling ex25.act for release

ERROR: Error when compiling ex25 module: Compilation error

Escaping type variable E_3
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

actonc exited with code:  1  terminated with signal: 0
kll@Kristians-MacBook-Air typeerrors %  
```

I encountered this in a larger program - the issue is that I really wanted a `list[Bar]` but accidentally wrote `[Bar]` and got this type error without a source location, so quite hard to pin down. Can we include the source location?

Assigning you @sydow in case you want to take a look or punt to @nordlander

**Comment by sydow** [comment]
I have a fix for this bug but want to hear comments from @nordlander before merging.

I think the error in the example should be a syntax error rather than a type error. As it stands, [Bar] does parse as a valid type, interpreted as Sequence[Bar]. This seems to be a reminiscence of an early idea to have convenient syntax for Sequences (and Sets and Mappings) which I think we have abandoned. So I have changed the Parser so that the above example gives the message

acton> actonc newexamples/bug1963.act 
Building file newexamples/bug1963.act

ERROR: Error when compiling bug1963 module: Syntax error

newexamples/bug1963.act:2:30:
  |
2 |     def __init__(self, bars: [Bar]):
  |                              ^^^^
unexpected "[Bar"
expecting type

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

acton> actonc newexamples/bug1963.act 
Building file newexamples/bug1963.act

ERROR: Error when compiling bug1963 module: Syntax error

newexamples/bug1963.act:2:30:
  |
2 |     def __init__(self, bars: [Bar]):
  |                              ^^^^
unexpected "[Bar"
expecting type

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

If we instead change the type of parameter bars to Sequence[Bar], syntax is ok and we do get an escaping type variable error. I have added source location to this, so  the error message is now what the issue asks for:

acton> actonc newexamples/bug1963.act 
Building file newexamples/bug1963.act
  Compiling bug1963.act for release

ERROR: Error when compiling bug1963 module: Compilation error
  |
2 |    def __init__(self, bars: Sequence[Bar]):
3 |        self.bars = bars
4 |
  | ...
  |
Escaping type variable

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

The location is maybe not as precise as one could hope for, but I think it is OK.

Comments?

**Comment by nordlander** [comment]
I'm all in favor. The [T] syntax for sequences is a nice feature in Haskell, but since Python's annotation language has adopted [ ] for type application it doesn't make sense any more to pursue the sequence idea in Acton. So let's drop it!
