### ISSUE TITLE
Type signature of lists & dicts?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#349]
I'm a little surprised by the type signature for a function that expects a list.

```
def foo(a):
    print(str(a[0]))

actor main(env):
    print("Hello " + env.argv[1] + "!")
    foo([1123.4, 213])
    await async env.exit(0)
```

signature is `Indexed[Number, value]`
```
kll@Boxy:~/terastream/acton/examples$ actonc --root main hello.act --sigs

#################################### sigs:

foo : (Indexed[Number, value]) -> None

actor main (Env):
    pass
```

In Python the type is called `List`. Why do we call it something else? Is this expected?

**Comment by plajjan** [comment]
I see essentially the same thing for dicts, which get `Indexed[str, value]` instead, so `str` rather than a `Number`.

**Comment by nordlander** [comment]
It's because `foo`'s parameter `a` isn't required to be a list just because we're indexing into it. The function could be given a `str` argument and it would work just as well. Or indeed a `dict`. In fact, it works for every argument that has a `__getitem__` method whose argument is a `Number` and whose result is a `value` – that is, any type that implements the `Indexed[Number, value]` protocol. An argument of type `list[float]` is certainly one such example, but so is a `str`. Or a `dict[int,bool]`. Or ...

Two more things to note:
1. The type of the indices isn't restricted to `int` just because `0` is used as a index – this is a result of our overloaded literal constants (hence `Number` in the signature above).
2. The data accessed at index `0` is only required to be convertible to a `str`, which holds for all types in the Acton type system. Hence `value`, which is the very top of our class hierarchy. (The class `object`, which represents the subset of mutable values in Acton, is one level below the top.)

**Comment by plajjan** [comment]
Thanks for answer. Closing.
