### ISSUE TITLE
Assembler / Compilation problems on older Ubuntu / Debian versions

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#381]
It seems we have problems compiling Acton on older versions of Ubuntu & Debian. Presumably with an older build toolchain. @aagapi saw it on Ubuntu 18.04 (also see #378). I have seen it on debian:stretch.

Here's a simplified example, compiling our builtin.c using minimum set of flags and we see errors like this:
```
root@06131d06e20b:/acton# cc -c builtin/builtin.c -obuiltin/builtin.o
/tmp/ccRKf4UY.s: Assembler messages:
/tmp/ccRKf4UY.s:241: Error: junk `(%rip)' after expression
/tmp/ccRKf4UY.s:298: Error: operand type mismatch for `call'
/tmp/ccRKf4UY.s:308: Error: operand type mismatch for `call'
/tmp/ccRKf4UY.s:335: Error: junk `(%rip)' after expression
/tmp/ccRKf4UY.s:335: Error: operand type mismatch for `lea'
/tmp/ccRKf4UY.s:343: Error: junk `(%rip)' after expression
/tmp/ccRKf4UY.s:350: Error: operand type mismatch for `call'
/tmp/ccRKf4UY.s:356: Error: operand type mismatch for `call'
/tmp/ccRKf4UY.s:362: Error: operand type mismatch for `call'
/tmp/ccRKf4UY.s:404: Error: junk `(%rip)' after expression
/tmp/ccRKf4UY.s:404: Error: operand type mismatch for `lea'
....
```

I've commented things out etc and it appears that the error stems from the use of `$NEW`. For example in `builtin/class_hierarchy.c`, we have the following:
```
$Serializable $Serializable$new() {
  return $NEW($Serializable);
}
```
if I simply comment out this, we get fewer errors. Leaving any use of `$NEW` results in assembler errors.

This is the definition in `builtin/common.h`:
```
#define $NEW($T, ...)       ({ $T $t = malloc(sizeof(struct $T)); \
                               $t->$class = &$T ## $methods; \
                               $t->$class->__init__($t, ##__VA_ARGS__); \
                               $t; })
```

Anything obviously wrong? ;)

**Comment by plajjan** [comment]
@nordlander or @sydow, can you discern why the above would fail? or maybe @aagapi too, since you're a C ninja :)

**Comment by nordlander** [comment]
Seems like the C compiler in use might have a bug in its handling of macro varargs, or in the operator that concatenates macro strings (first occurrence of ## above). Technically it would be possible to circumvent the problem by manually inlining every occurrence of $NEW in the builtin dir, but it amounts to myriads of places in at least 22 files (not counting the test cases).

What gcc version is running here? Does it have a known issue with macro varargs?

**Comment by nordlander** [comment]
BTW, I think the terms used by the gcc docs use for the features in question are _variadic macros_ and _token concatenation_.

**Comment by plajjan** [comment]
cc version:
```
root@5adaf600f81a:/acton# cc --version
cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@5adaf600f81a:/acton#
```

Just trying to nail down which line produces the error, I tried removing stuff.

This removes the warning completely:
```
#define $NEW($T, ...)       ({ $T $t = malloc(sizeof(struct $T)); \
                               $t; })
```

well, you get a different kind of error in the end...

This emits the same error as the complete block, so it seems it is the second line here that is causing us troubles.
```
#define $NEW($T, ...)       ({ $T $t = malloc(sizeof(struct $T)); \
                               $t->$class = &$T ## $methods; \
                               $t; })
```

That line isn't using the variadic macro, right? That's just on the line after, so this is maybe simpler? Or am I reasoning about this wrong?

**Comment by nordlander** [comment]
The macro def is actually spread out over 4 lines (notice the \ before each newline), so it's still the expansion of the variadic $NEW that triggers the bug. But in any case I think you've actually narrowed down the problem to the token concatenation operator, since that's the only thing one can suspect on line 2.

What happens here is that if `$NEW` is invoked as `$NEW($dict,hashwit,wit,iterable)`, for example, the second line of the expanded code will become
```
    $t->$class = &$dict$methods;
```
The `##` operator in the macro simply concatenates the first macro parameter `$T` (which has value `$dict` in the example) with the constant string token `$methods`, removing any white space in the process.

So it appears that token concatenation is broken in gcc 6.3.0, or maybe specifically concatenation of tokens that start with `$`. Can you run gcc with the `-E` option on file `builtin/dict_impl.c` and search for the pattern `51 "dict_impl.c` in the output? If that works it would be interesting to see the 3 lines that follow the matched text.

**Comment by plajjan** [comment]
Yes yes, I know it's a single macro. After finding it had to do with `$NEW`, I was just trying to nail down which part of it was causing the assembler errors. The statements in it are after all spread out across multiple lines, so I still think it makes sense to refer to them as lines :)

I don't see a `51 "dict_impl.c` line at all. I created a gist of the `dict_impl.c` file I have in this branch (just to be sure there are no differences) and the output of gcc -E on that file, see https://gist.github.com/plajjan/205b11ea1d691219447fa3544dda535a

**Comment by nordlander** [comment]
Ah, I should ha realized that without a previous `cd builtin`, the pattern to look for must be `51 "builtin/dict_impl.c`. But anyway, the generated output looks just right; in particular the statement `$t->$class = &$dict$methods` looks exactly as it should.

Still, the bad assembler output must somehow be caused by code like line 7557 in the gist above, and similar places. Perhaps the next step drilling forward would be to inspect the actual assembly code. Running `gcc -S builtin/builtin.c -o tmp.s` should produce a file `tmp.s` with the same contents as the file `/tmp/ccRKf4UY.s` above. Would be interesting to see what lines 241, 298, etc, actually look like.

Googling the error text shows some indication the problem is related to the Intel vs. AT&T assembly syntax traditions, but since it's all triggered by a specific line in the `$NEW` macro there must be more to it...

**Comment by plajjan** [comment]
@nordlander IIRC you have docker installed on your machine, no?

Go into your acton dir, then:
`docker run -it --name stretch -v $(pwd):/src debian:stretch`

and you will get a shell in a docker container running debian stretch, which has this problem. Run `apt-get update` and install gcc, make etc `apt-get install gcc make`; then try building.

I ran the command you provided to produce tmp.s and uploaded it to the same gist - https://gist.github.com/plajjan/205b11ea1d691219447fa3544dda535a

**Comment by aagapi** [comment]
I can confirm the assembler error also happens on a clean Ubuntu 18.04.6 LTS install, which comes with gcc 7.5.0 (so newer gcc than Kristian's 6.3.0 on the old Debian). The error does not happen on Ubuntu 20.04.3 LTS, which comes with gcc 9.3.0. So the problem was fixed somewhere between gcc versions 7.5.0 and 9.3.0.

By the way, the build from source still fails on Ubuntu 20.04.3 LTS after that, due to 2 reasons:
- 3 lines in builtin/minienv.c give warning "ignoring return value of [...], declared with attribute warn_unused_result". This is fixable by not treating -Wunused-result as a build error in the Makefile
- The lack of libmd dependency on stock Ubuntu installations (fixable by adding 'apt install libmd-dev' in dependency list for Ubuntu)

Also, for the build to work in the beginning on Ubuntu (18 or 20), it required a "sudo stack upgrade" before running make, as on the stack version installed by default by the Ubuntu package manager, the download of the Haskell lts-18.12 build plan was failing druin make from raw.githubusercontent.com. This is fixed by bumping up the Haskell stack version.

**Comment by plajjan** [comment]
Should we just switch to compiling things with clang instead of gcc?

**Comment by plajjan** [comment]
So I'll close this with a wont-fix.

Out of all the things we need to fix around Acton, attempting some level of compatibility with older distributions is just not very important. If someone is reading this, thinking that it should be fixed and you are willing to spend the time, feel free; go ahead. The contribution is very welcome. However, for the core Acton dev team, we need to prioritize other things. This is so low priority that it won't get any attention in years, thus I prefer closing it.
