### ISSUE TITLE
Generate env.c

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#485]
The environment stuff is built into Acton and consists of manually written C code. One of the big challenges we have with this is that the manually written C code needs to match the code that actonc generates. Simple in practice, but as we improve actonc and our output changes ever so slightly, we must keep env.c up to date. As it turns out, this is a challenge and we have failed numerous times.

Can we improve the situation and generate parts of env.c? I think so.

My idea is roughly:

1. rename env.c to env_in.c
2. generate env_cgen.c from stdlib/src/__builtin__.act
3. extract function signatures from env_cgen.c and env_in.c
   - error out if mismatch - they must match!
4. remove functions in env_cgen.c that match function signatures in env_in.c
5. produce env.c by merging env_cgen.c and env_in.c

- [x] not possible to stub & cgen compile stdlib/src/__builtin__.act #486 
- [ ] should we cgen entire stdlib/src/__builtin__.act or first cut out just the Env part of it? including only:
  - actor Env
  - actor Connection
  - actor RFile
  - actor WFile

I did try to extract just the Env part into a new act file, like and stub&cgen compile that but got another error:
```
kll@Boxy:~/terastream/acton/stdlib/src$ ../../dist/bin/actonc --stub --cgen env.act

******************** Type error
 10:36-40
   |
10 |    openR        : action(str) -> ?RFile
   |                                   ^^^^^
Cannot infer RFile < __builtin__.RFile

kll@Boxy:~/terastream/acton/stdlib/src$ 
```

**Comment by plajjan** [comment]
@nordlander since the goal is to produce env.c, can you comment on how we should generate this from __builtin__.act? Is it a valid idea to first extract from the source __builtin__.act only the Actors Env, Connection, RFile & WFile (these are the things implemented in env.c, right!?) or must __builtin__.act be compiled as a whole? I mean, at the point where I am compiling it, we have already built a __builtin__.ty for our own system - we should already be "bootstrapped" in that sense, so I reckon I should be able to extract parts into a env.act and stub+cgen that to get the C output I want. Thoughts?

**Comment by plajjan** [comment]
Differently phrased, should env.c contain the lambdas etc for things defined in __builtin__.act, i.e. builtins, but that are not part of what is otherwise thought of as the environment?

env.c should only contain a subset of the things in `__builtin__.act`, right? THe things that pertain to the environment actors Env, Connectionm, RFile & WFile... right?

**Comment by plajjan** [comment]
@nordlander I'm not quite done yet but these are the function signature differences, which I suspect you can start working on right away, anyway.

```
ERROR: $Env$__init__ return type differs: ($NoneType) vs ($R)
ERROR: $Env$__init__ args differs: ($Env __self__, $list argv) vs ($Env __self__, $list args, $Cont c$cont)
ERROR: $Env$newact return type differs: ($Env) vs ($R)
ERROR: $Env$newact args differs: ($list p$1) vs ($list args, $Cont c$cont)
ERROR: $Connection$__init__ return type differs: ($NoneType) vs ($R)
ERROR: $Connection$__init__ args differs: ($Connection __self__, int descr) vs ($Connection __self__, $Cont c$cont)
ERROR: $Connection$newact return type differs: ($Connection) vs ($R)
ERROR: $Connection$newact args differs: (int descr) vs ($Cont c$cont)
ERROR: $RFile$__init__ return type differs: ($NoneType) vs ($R)
ERROR: $RFile$__init__ args differs: ($RFile __self__, FILE* file) vs ($RFile __self__, $Cont c$cont)
ERROR: $RFile$newact return type differs: ($RFile) vs ($R)
ERROR: $RFile$newact args differs: (FILE* file) vs ($Cont c$cont)
ERROR: $WFile$__init__ return type differs: ($NoneType) vs ($R)
ERROR: $WFile$__init__ args differs: ($WFile __self__, int descr) vs ($WFile __self__, $Cont c$cont)
ERROR: $WFile$newact return type differs: ($WFile) vs ($R)
ERROR: $WFile$newact args differs: (int descr) vs ($Cont c$cont)
```

**Comment by nordlander** [comment]
These differences all concern constructors for the built-in actors Env, Connection, RFile and WFile. The compiler generated signatures are technically correct, but since these actors are just intended to be instantiated by hand-written code in env.c, the constructor signatures should really not have been part of the compiler output at all. Note that it's not just the CPS parameters and results that make the compiler output different, it's also the absence of the true constructor parameters 'descr' and 'file' -- parameters that can only be given meaningful values inside env.c.

The correct fix to this problem would thus be to make the compiler avoid generating constructor signatures for actors that we intend to be abstract. Whether this should be inferred from the --stub flag or something else must be discussed, though.

**Comment by plajjan** [comment]
@nordlander well we can just selectively filter them out in the gen_env.py script to avoid getting these errors!? Is it general enough that it is worthwhile having the compiler not emit these? and if it doesn't emit it during --cgen, how are we supposed to write new actors like this? I've always imagined the --cgen output as a skeleton where you then modify the function bodies etc

The lines say "ERROR" but the script continues processing, so this is more of a warning. Nonetheless, the combination of generated and manual code right now in the branch does not 
compile. Have I generated too much and should back down a bit? Or is the fix to move forward closer to the generated code?

**Comment by nordlander** [comment]
@plajjan The core issue I'm touching upon is that we actually don't want it to be possible to instantiate Env, Connection, RFile and WFile actors from within Acton. So it's really a question of what we put in the .ty file when we compile with the --stub flag, and how we programatically identify an actor that's just meant to be an interface.

Currently we don't have any notion of an "abstract" actor, although we do have something in that vein for classes (any class for which there exists a method signature without an accompanying method definition will be impossible to instantiate). Maybe we should provide something similar for actors?

But coming back to the core issue of checking env.c: it doesn't matter so much if the script checks signatures that shoudn't really have been emitted, as long as it doesn't overwrite any manually crafted code. Treating "ERROR" as a warning is ok, it's still the C programmer's responsibility to understand what it all means. Moreover, having a compiler-generated constructor function isn't strictly necessary, as it's always possible to utilize the macro $NEWACTOR in C and invoke __init__ on the new instance manually. Which the current code does in the manually written constructors.

I'll take a look at the C compiler errors and see what they imply.

**Comment by plajjan** [comment]
@nordlander right, so the script does not emit functions that already exist, which it determines by looking at the name of the function. It does check the signature and warns about this mismatch but then accepts and proceeds.

However, you are talking about CPS & not-CPS style. I guess the script/actonc will emit some other functions which are meant to be used the CPS way and the manual functions are non-CPS? I dunno which are which, so hard for me to tell. Maybe they don't hurt, since they are not called anyway?

If these functions are correct, it sounds all the more like I should just back out changes until env.c/.h compile again...

**Comment by nordlander** [comment]
Yep, hold on for the moment!

The distinction between CPS or not is of course very important in general, but for functions that aren't supposed to be called by compiled code it's all in the hands of the C programmer. So in parallel with the current issue we should also plan for (1) find a way of making actor types abstract, and (2) update the CPS conversion slightly so that it can take the kind of shortcuts we currently do manually. None of these tasks are critical, though.

**Comment by plajjan** [comment]
Agreed, none of that is critical.

I had a look at the current errors and I'm not so sure that it actually has anything to do with any existing code! It appears that all the errors are in newly generated functions! I find this weird. I presumed that the errors we would see would be from mismatches between generated code and manually written code.

There used to be 14lambda but now it goes up to like 26. Looks like some of the newly generated functions are wrong!? Where did these functions come from? Have we been missing so many? What are they related to? Shoudln't we see linker errors if we tried to call these?

Would be good if you had a look at it @nordlander. If it's something bigger to fix, we can just comment out these new functions for the time being.

**Comment by nordlander** [comment]
Ah, more lambdas are created because actor initiation is nowadays executed as synchronous messages, which in turn creates extra continuations. And all of this happens inside the actor constructors we just concluded shouldn't really have been exposed!

I guess the script could easily be tweaked to filter out these lambdas (and four plain functions that go with them), although I also realize that it wouldn't take much for me to fix the problem closer to its root by just silencing the generation of actor constructors when --stub is on. Although this probably isn't the approach to "abstract actors" we want in the long term, it is definitely good enough for now. 

I'll get right to it!

**Comment by plajjan** [comment]
I'm not sure I grasp all the details, but is suppressing this generally correct and not just for env? I mean, if I want to write module Foo in C that looks like an actor won't I need those functions that you are talking about suppressing?

Looks like the --gen option (to generate code) is less and less useful, too many exceptions... but I guess that is fine. We can settle for the --check option. It could just say "missing function" for the new lambda bla bla and that would be it. We could include all the current exceptions, so it becomes more of a warning if something happens.

All this is to help us maintain env. I don't want to spend more time on this gen / check script than we spend on actually maintaining env, so we need a lagom approach.

**Comment by nordlander** [comment]
I've implemented a (weak) support for abstract actors, by which we understand actors with one or more method defined just as a signature. Such actors are currently only allowed if we compile with --stub. The only catch is that these abstract methods currently don't leave any trace at all in the generated code, which I guess is something of a drawback....

I'll keep working on it, but hopefully you be able to resume your work in parallel!

**Comment by nordlander** [comment]
Short update: rather than also generating C code for actor methods only defined in terms of signatures, I decided to keep code generation as it is and instead add some redundant signatures to the env actors just to make them abstract. This makes the `--stub` C output close to what we want, at the expense of an obscure signature `_abstract : () -> None` in some actor interfaces. But as long as no-one attempts to call that silly method everything is benign. And we must of course develop a better syntax for expressing abstract actors down the line.
