### ISSUE TITLE
Eq/Ord instances for container types

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#690]
When writing tests for builtin_auto I stumbled on the fact that lists do not implement the Eq protocol! This should of course be added immediately, but let us think about what else could/should be done at the same time. 

Of course, we will require that the type parameter of elements will implement Eq.

- Should lists implement Ord if the parameter type does? The natural "less than" would be lexicographic order. 
- Sets already implement Ord. Here "less than" is subset.
- Should dictionaries implement Eq? Might be useful, but I am less convinced by Ord. When is d1 less than d2? Probably if every key in d1 is present in d2, but should the values be equal or less than? I think the former; a subdictionary gives info about fewer keys, but the same info. One needs an Eq constraint on the value type.
- What about tuples? I guess one would want Eq for tuples if the element types support it, but we don't even have the syntax for writing such an extension in __builtin__.act, even for fixed length tuples (e.g. pairs or triples).

I would propose to implement Ord for lists and dictionaries as above and leave tuples for the future. I volunteer to do it but wait for your comments.

**Comment by plajjan** [comment]
Eq for lists, sets, dicts all make sense IMHO

I really don't have any sort of opinion on Ord for any of these. I don't think I've ever used it and haven't spent enough time meditating on what it even means to have an opinion. @nordlander would need to chime in.... or you go ahead with Eq for now and do Ord later!?

**Comment by nordlander** [comment]
I'm all in favor of having both Eq and Ord, but of course Eq has a higher priority!

**Comment by nordlander** [comment]
But the tuple case is interesting! In fact, it's an instance of a general problem that languages like Haskell has when abstracting over tuples, but where we might have a chance of improving things because our tuples are based on rows. It also touches on the fact that from a Python perspective it might be reasonable to expect some means of doing regular computations over tuples, like map and apply.

However, I suppose this effort will have to wait until we're done solving more urgent needs. Which is to say that I think any temporary hack needed to obtain equality for tuples is acceptable, as long as we don't forget our long-term goal is still a proper (and beautiful!) solution.

**Comment by plajjan** [comment]
I'd like to close this issue and create a new one, more refined, to the items that still remain. @sydow do you think you can do that? You have the subject matter expertise here... :)

**Comment by sydow** [comment]
Ord instances for lists and docts are now implemented (pull request #719). We close this issue now; I will open a  new one for tuples.
