### ISSUE TITLE
How to terminate actor?

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#705]
I don't think we have language syntax for terminating an actor... how should it be done?

**Comment by plajjan** [comment]
Removing all references to an actor means it should be garbage collected, so that's the way to terminate an actor! If we were to introduce a more explicit `shutdown()` or similar, we'd end with the problem of what to do with all the existing references to a now defunct actor. It's not the route we want to go. Closing.

**Comment by nordlander** [comment]
Exactly!

One bordeline issue is however what to do if the only live references to an actor stem from the timer/ready queues. Part of me wants to argue that such an actor is still live, and thus shouldn't be garbage collected. But a consequence of that would also be that a periodic actor wouldn't be stoppable just by dropping its reference; it would have to be explicitly told not to issue its next **after** call in order to stop. Perhaps this is an unexpected behavior. On the other hand, the opposite behavior would imply that choices made within the garbage collector, like _when_ to collect, could affect the observable output of an Acton system. Not a desirable property either.

A borderline issue, as it were, to be returned to when we implement the GC.

**Comment by plajjan** [comment]
That's a little trickier but I don't think it really changes anything - it should still be GCed, even if it has stuff on the timerQ (which should then be cleaned up). Like, if you have an actor that is doing something periodically using after and you want it to keep doing that... then don't drop the reference to it? That's a simple enough model that I don't see any real argument in the other direction?

**Comment by nordlander** [comment]
Well, the argument against is exactly that it makes obervable behavior depend on the GC.

Imagine a periodic actor that prints "Hello" every second. Its parent keeps a reference to it, but then drops the reference in response to some external event. How many "Hello" will be printed after that event was received? The answer is that it can be _any number_, since it's now dependend on the GC's internal behavior.

The GC must also strike a balance between speed and CPU load, so we can't really expect it to be "maximally fast" when it comes to cleaning up orphaned actors. In fact, in a system with very low memory consumption, there could be hours/days/... between the orphaning of an actor and the next GC run.

So to obtain a controlled behaviour in cases like this, the programmer would have to implement some explicit stopping procedure. A simple solution could let the periodic actor also receive a message that changes its state in such a way that the next periodic invocation understands it shouldn't re-execute its **after** statement. And with an explicit mechanism in place, I think it's debatable whether GC'ing the timer queue really offers any extra benefits.

**Comment by plajjan** [comment]
Perhaps actor references are ref counted anyway, like isn't that the only feasible approach in a distributed system? So actor will be immediately collected when dereferenced.
