### ISSUE TITLE
Handle DB errors / return codes of DB client API in RTS

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#939]

**Comment by plajjan** [comment]
It seems there are DB client API functions that do not return errors the way they should, for example https://github.com/actonlang/acton/blob/main/backend/client_api.c#L1635. Shouldn't that be `return NO_QUORUM_ERR;` ?

**Comment by aagapi** [comment]
> It seems there are DB client API functions that do not return errors the way they should, for example https://github.com/actonlang/acton/blob/main/backend/client_api.c#L1635. Shouldn't that be `return NO_QUORUM_ERR;` ?

Fixed by https://github.com/actonlang/acton/pull/945. Thank you for noticing this. There were 4 functions in the API that do non-range search of DB rows in the client API did not return a status, but a pointer to the row, an NULL if this fails. Changed them to also return status. I also changed the DB unit tests, however these functions were not currently used in the Acton RTS.

**Comment by plajjan** [comment]
@aagapi remote_new_txn also returns uuid of transaction rather than a status. Should it too be changed?

**Comment by aagapi** [comment]
> @aagapi remote_new_txn also returns uuid of transaction rather than a status. Should it too be changed?

This is an interesting one. In principle that function call creates a new transaction state locally, including a new UUID txnid generated on the client side. While UUID collisions are *very very* unlikely, it then still checks for UUID collisions on a quorum of servers to make sure a previous txn doesn't exist with the same ID (this is more to future-proof the code in case we decide to use something else than UUIDs for txn_ids). Even in the very unlikely case a collision is detected on the servers, the function internally retries with a new generated UUID until success (no collision).
So the only reason this function would ever fail is actually for a lack of quorum (and again the check of collisions on the servers is probably superfluous in the first place if we assume no collisions from the UUID library). This is the reason I chose not to include a status and simply return NULL in the case of a lack of quorum (since the status can only ever be 0 or NO_QUORUM_ERR), to make calling the init function for a txn simpler / less tedious.

**Comment by plajjan** [comment]
Great work @aagap!! 🎉

Closing this issue.
